### ISSUE TITLE
problem with using the "depth_multiplier" argument

### ISSUE THREAD

**Issue by mohammed-Emad** [vietdzung/fall-detection-two-stream-cnn#1]
Hi thank you for the wonderful work
There is a problem with using the `depth_multiplier` argument
This is in the next line
[#L19](https://github.com/vietdzung/fall-detection-two-stream-cnn/blob/master/train_model.py#L19)

```python3
base_model = MobileNetV2(
        input_shape = (224, 224, 3), alpha = 1.0, depth_multiplier = 1,
        include_top = False, weights = "imagenet"
    )
```
It may appear like the following error

`TypeError: ('Invalid keyword argument: %s', 'depth_multiplier')
`
It seems that he has been stopped summoning him in recent versions of the kers library

> cut ... _In the docs (https://keras.io/applications/#mobilenetv2), depth_multiplier is listed and used as an argument to keras.applications.MobileNetV2, even though it is not implemented in ....._ 

see https://github.com/keras-team/keras/issues/12327

Please be amended or removed, if it is worth, from your point of view.
__
Another thing .. What about the training data, are there any tips on processing more training data, or can you share your data?

Thanks again
Mohammed Emad:

**Comment by mohammed-Emad** [comment]
I apologize for the data Did not notice that you are using

>  "FDD [dataset"](http://videodatasets.org/)

Sorry, it is now clear

**Comment by vietdzung** [comment]
Hey, thanks for taking a look and pointing out the bug, I will fix it soon-ish now that summer has arrived. I used the FDD dataset because it had bounding boxes on the human moving around. There are 2 other fall video datasets but they are not fully labelled.

**Comment by mohammed-Emad** [comment]
thanks @vietdzung
